### ISSUE TITLE
1.1 - User Input - Stanley McMillan

### ISSUE THREAD

**Issue by mcmillanator** [tiy-chs-ruby/assignments-june-2015#5]
My Project Link https://github.com/mcmillanator/1.1-User-Input
- [x] Create a new Issue with these tasks!
- [x] Use the Github web interface to create a repository called `1.1-User-Input`
- [x] Use the Github web interface to create a branch called on `1.1-User-Input` called `<initials>-develop`
- [x] In Github, open a PR from `<initials>-develop` into `master`
- [x] Create the Quick Star Wars Character test
  - [x] Checkpoint: Create `assignment.rb`
  - [x] Checkpoint: Store a person's name from a prompt
  - [x] Checkpoint: Store a person's legal preference
  - [x] Checkpoint: Perform logic on the legal preference
  - [x] Checkpoint: Return one of the required strings back to the user.
  - [x] Checkpoint: Commit `assignment.rb`
  - [x] Complete: Pushed `assignment.rb`

**Comment by mcmillanator** [comment]
TODO:
- [x] do not accept empty name
- [x] do not accept empty pref
- [x] do not accept a pref that is not 1-4

**Comment by rpearce** [comment]
Your code is simple and therefore :+1:.

There is an issue, though: each assignment needs to be done in a branch called `dev`, with a pull request from `dev` into `master`. The purpose of this is so that I can comment on any line of your code that I need to, you can make changes and then we can merge up in to master when you are ready.

**Comment by rpearce** [comment]
Don't worry about it for this one, but try to remember for the future so I can help hone those Ruby skills.

**Comment by mcmillanator** [comment]
:+1:.
